/**
 * Map institute names (or substrings) to their state.
 * Used to fill in missing state data in the cutoff DB.
 */
const INSTITUTE_STATE_MAP: [string, string][] = [
  // IITs
  ['IISc Bangalore', 'Karnataka'],
  ['IIT BHU', 'Uttar Pradesh'],
  ['IIT Bhilai', 'Chhattisgarh'],
  ['IIT Bombay', 'Maharashtra'],
  ['IIT Delhi', 'Delhi'],
  ['IIT Dharwad', 'Karnataka'],
  ['IIT Gandhinagar', 'Gujarat'],
  ['IIT Goa', 'Goa'],
  ['IIT Guwahati', 'Assam'],
  ['IIT Hyderabad', 'Telangana'],
  ['IIT ISM Dhanbad', 'Jharkhand'],
  ['IIT Indore', 'Madhya Pradesh'],
  ['IIT Jammu', 'J&K'],
  ['IIT Jodhpur', 'Rajasthan'],
  ['IIT Kanpur', 'Uttar Pradesh'],
  ['IIT Kharagpur', 'West Bengal'],
  ['IIT Madras', 'Tamil Nadu'],
  ['IIT Mandi', 'Himachal Pradesh'],
  ['IIT Palakkad', 'Kerala'],
  ['IIT Patna', 'Bihar'],
  ['IIT Roorkee', 'Uttarakhand'],
  ['IIT Ropar', 'Punjab'],
  ['IIT Tirupati', 'Andhra Pradesh'],
  // NITs
  ['NIT Agartala', 'Tripura'],
  ['NIT Calicut', 'Kerala'],
  ['NIT Delhi', 'Delhi'],
  ['NIT Durgapur', 'West Bengal'],
  ['NIT Goa', 'Goa'],
  ['NIT Hamirpur', 'Himachal Pradesh'],
  ['NIT Jamshedpur', 'Jharkhand'],
  ['NIT Karnataka', 'Karnataka'],
  ['NIT Kurukshetra', 'Haryana'],
  ['NIT Manipur', 'Manipur'],
  ['NIT Meghalaya', 'Meghalaya'],
  ['NIT Mizoram', 'Mizoram'],
  ['NIT Nagaland', 'Nagaland'],
  ['NIT Patna', 'Bihar'],
  ['NIT Puducherry', 'Puducherry'],
  ['NIT Raipur', 'Chhattisgarh'],
  ['NIT Rourkela', 'Odisha'],
  ['NIT Silchar', 'Assam'],
  ['NIT Sikkim', 'Sikkim'],
  ['NIT Srinagar', 'J&K'],
  ['NIT Surat', 'Gujarat'],
  ['NIT Surathkal', 'Karnataka'],
  ['NIT Tiruchirappalli', 'Tamil Nadu'],
  ['NIT Trichy', 'Tamil Nadu'],
  ['NIT Uttarakhand', 'Uttarakhand'],
  ['NIT Warangal', 'Telangana'],
  ['NIT Arunachal', 'Arunachal Pradesh'],
  ['MANIT Bhopal', 'Madhya Pradesh'],
  ['MNNIT Allahabad', 'Uttar Pradesh'],
  ['MNIT Jaipur', 'Rajasthan'],
  ['SVNIT Surat', 'Gujarat'],
  ['VNIT Nagpur', 'Maharashtra'],
  // Full-name IIT variants (no comma format)
  ['Indian Institute of Technology Bombay', 'Maharashtra'],
  ['Indian Institute of Technology Delhi', 'Delhi'],
  ['Indian Institute of Technology (BHU) Varanasi', 'Uttar Pradesh'],
  // Other specific institutes
  ['Delhi Technological University', 'Delhi'],
  ['Netaji Subhas University of Technology', 'Delhi'],
  ['Jawaharlal Nehru University', 'Delhi'],
  ['Gautam Buddha University', 'Uttar Pradesh'],
  ['Birla Institute of Technology', 'Jharkhand'],
  ['CU Jharkhand', 'Jharkhand'],
  ['Central University of Haryana', 'Haryana'],
  ['Central University of Jammu', 'J&K'],
  ['CSVTU Bhilai', 'Chhattisgarh'],
  ['Chhattisgarh Swami', 'Chhattisgarh'],
  ['Ghani Khan', 'West Bengal'],
  ['Gurukula Kangri', 'Uttarakhand'],
  ['Carpet Technology, Bhadohi', 'Uttar Pradesh'],
  ['Handloom Technology', 'Uttar Pradesh'],
  ['Salem', 'Tamil Nadu'],
  ['Sri City', 'Andhra Pradesh'],
  ['Chittoor', 'Andhra Pradesh'],
  ['Dharwad', 'Karnataka'],
  ['Sonepat', 'Haryana'],
  ['Kottayam', 'Kerala'],
  ['Raichur', 'Karnataka'],
  ['Sagar', 'Madhya Pradesh'],
  ['Manipal', 'Karnataka'],
  ['Kundli', 'Haryana'],
  ['Thanjavur', 'Tamil Nadu'],
  ['Shillong', 'Meghalaya'],
  ['Tezpur', 'Assam'],
  ['Vijayawada', 'Andhra Pradesh'],
  ['Indore', 'Madhya Pradesh'],
  ['Fursatganj', 'Uttar Pradesh'],
  ['Amethi', 'Uttar Pradesh'],
  ['Greater Noida', 'Uttar Pradesh'],
  ['Varanasi', 'Uttar Pradesh'],
  ['Malda', 'West Bengal'],
  ['Haridwar', 'Uttarakhand'],
  ['NITTTR', 'Madhya Pradesh'],
  ['Puducherry', 'Puducherry'],
  ['Kokrajar', 'Assam'],
  ['Kokrajhar', 'Assam'],
  ['Guwahati', 'Assam'],
  ['Bhilai', 'Chhattisgarh'],
  ['Kanpur', 'Uttar Pradesh'],
  ['Kharagpur', 'West Bengal'],
  ['Madras', 'Tamil Nadu'],
  ['Palakkad', 'Kerala'],
  ['Jammu', 'J&K'],
  ['Goa', 'Goa'],
  // Keyword-based fallbacks
  ['Agartala', 'Tripura'],
  ['Ahmedabad', 'Gujarat'],
  ['Aizawl', 'Mizoram'],
  ['Ajmer', 'Rajasthan'],
  ['Allahabad', 'Uttar Pradesh'],
  ['Aurangabad', 'Maharashtra'],
  ['Bangalore', 'Karnataka'],
  ['Bathinda', 'Punjab'],
  ['Bhopal', 'Madhya Pradesh'],
  ['Bhagalpur', 'Bihar'],
  ['Bhubaneswar', 'Odisha'],
  ['Bilaspur', 'Chhattisgarh'],
  ['Calicut', 'Kerala'],
  ['Chandigarh', 'Punjab'],
  ['Chennai', 'Tamil Nadu'],
  ['Cochin', 'Kerala'],
  ['Diu', 'Gujarat'],
  ['Gandhinagar', 'Gujarat'],
  ['Gorakhpur', 'Uttar Pradesh'],
  ['Gwalior', 'Madhya Pradesh'],
  ['Howrah', 'West Bengal'],
  ['Shibpur', 'West Bengal'],
  ['Silchar', 'Assam'],
  ['Rourkela', 'Odisha'],
  ['Jamshedpur', 'Jharkhand'],
  ['Kurukshetra', 'Haryana'],
  ['Manipur', 'Manipur'],
  ['Durgapur', 'West Bengal'],
  ['Hamirpur', 'Himachal Pradesh'],
  ['Nagpur', 'Maharashtra'],
  ['Patna', 'Bihar'],
  ['Surathkal', 'Karnataka'],
  ['Meghalaya', 'Meghalaya'],
  ['Mizoram', 'Mizoram'],
  ['Nagaland', 'Nagaland'],
  ['Sikkim', 'Sikkim'],
  ['Uttarakhand', 'Uttarakhand'],
  ['Arunachal', 'Arunachal Pradesh'],
  ['Agartala', 'Tripura'],
  ['Srinagar', 'J&K'],
  ['Jalandhar', 'Punjab'],
  ['Dhanbad', 'Jharkhand'],
  ['Roorkee', 'Uttarakhand'],
  ['Mandi', 'Himachal Pradesh'],
  ['Tirupati', 'Andhra Pradesh'],
  ['Imphal', 'Manipur'],
  ['Itanagar', 'Arunachal Pradesh'],
  ['Jabalpur', 'Madhya Pradesh'],
  ['Jalandhar', 'Punjab'],
  ['Jodhpur', 'Rajasthan'],
  ['Kalyani', 'West Bengal'],
  ['Kancheepuram', 'Tamil Nadu'],
  ['Kohima', 'Nagaland'],
  ['Kokrajhar', 'Assam'],
  ['Kolkata', 'West Bengal'],
  ['Kota', 'Rajasthan'],
  ['Kurnool', 'Andhra Pradesh'],
  ['Lucknow', 'Uttar Pradesh'],
  ['New Delhi', 'Delhi'],
  ['Pune', 'Maharashtra'],
  ['Raipur', 'Chhattisgarh'],
  ['Naya Raipur', 'Chhattisgarh'],
  ['Ranchi', 'Jharkhand'],
  ['Ropar', 'Punjab'],
  ['Srinagar', 'J&K'],
  ['Surat', 'Gujarat'],
  ['Thiruvananthapuram', 'Kerala'],
  ['Trivandrum', 'Kerala'],
  ['Tiruchirappalli', 'Tamil Nadu'],
  ['Una', 'Himachal Pradesh'],
  ['Vadodara', 'Gujarat'],
  ['Warangal', 'Telangana'],
  ['Hyderabad', 'Telangana'],
  ['Kashmir', 'J&K'],
  ['Rajasthan', 'Rajasthan'],
  ['Punjab', 'Punjab'],
  ['Longowal', 'Punjab'],
]

/**
 * Given an institute name, return its state.
 * Tries exact substring matches from most specific to least.
 */
export function resolveInstituteState(institute: string): string {
  if (!institute) return ''
  const lower = institute.toLowerCase()
  for (const [keyword, state] of INSTITUTE_STATE_MAP) {
    if (lower.includes(keyword.toLowerCase())) return state
  }
  return ''
}
